### ISSUE TITLE
npm install (or yarn) takes 362secs and almost 700mb 

### ISSUE THREAD

**Issue by amarinso** [devonfw/my-thai-star#155]
Category: enhancement

Trying out my-thai-star takes too long. 

This can not serve as ready-for-production sample

Is it really required to download the electron dependencies? can it be required as optional dependency or alternate package.json file?

**Comment by amarinso** [comment]
This only gets worse when working with docker and docker-compose because every time you get the build penalty for the image...

**Comment by hohwille** [comment]
Welcome to the ugly world of `npm`. The tool has already evolved a lot. However, still it is extraordinary greedy and wasteful with resources like bandwidth and storage. One might already complain about maven or gradle but at least these tools seem to have some kind of architecture and design while `npm` has grown from a hackish bunch of scripts and design is hard to add later on.

However, we ourselves can not easily redesign `npm` or speed up `docker`. The only thing we can do is trying to get rid of dependencies in `package.json`. Do you have concrete candidates that we could eliminate? Then we can discuss about them.
Otherwise this is a kind of ticket that will stay open for years without any progress.

**Comment by markusschuh** [comment]
There seem to be at least some [techniques](https://itnext.io/npm-install-with-cache-in-docker-4bb85283fa12) that help reducing the downloads from second `docker build` run onward. Of course, during base development there is no need to build a docker container that often - but even the final integration test should be bit quicker.

This needs a better sync of docker layers with the file system caching of `npm` - in this case. But I'd say, with `yarn` the challenge is similar. I have not yet tried the described setup. Just thought, I mention it here even without knowing for sure, it works.
