### ISSUE TITLE
"ng serve" does not work

### ISSUE THREAD

**Issue by amarinso** [devonfw/my-thai-star#156]
As my understanding is that devon4ng should be a good Angular citizen including the usage of @angular/cli I was expecting to clone the repo, npm install and ng serve

It does build the application, but that gives me this error on the console:
`external "require('url')":1 Uncaught ReferenceError: require is not defined `

**Comment by sjimenez77** [comment]
The error is caused by the no execution of the ```postinstall.js``` script needed to enable Electron in the Angular execution context. 

The Angular CLI is a powerful tool with lots of parameters and flags, and from some time ago we are using the npm scripts defined in the ```package.json``` in order to use and automate more complex features as PWA, testing alternatives and lately Electron. In many JavaScript projects the npm scripts are the reference for any developer, as it is the first place you should look. In any case I agree about the ```ng serve``` issue and we could try to find a more elegant alternative to add these features. 

Maybe we should discuss this special cases if they are not enough relevant and remove them or add them in separated branches too.
