### ISSUE TITLE
Find order by reference null does not return any values

### ISSUE THREAD

**Issue by vapadwal** [devonfw/my-thai-star#268]
Find order by reference null does not return any results

**Comment by Rohit90700** [comment]
Created PR - https://github.com/devonfw/my-thai-star/pull/292 for this issue

**Comment by ssarmokadam** [comment]
Need to verify if this issue is fixed.

**Comment by nilbarma** [comment]
The issue is not there anymore. I have tested it in postman. we need to pass the paging data in the body. Along with that if we pass any other reference like email or booking token, the search method works correctly. Also in the web page if we log in as waiter we can see that filter order  functionality is working perfectly.

**Comment by sujith-mn** [comment]
Can we have default pagination values if not supplied?
