### ISSUE TITLE
[API] GET api/services/rest/bookingmanagement/v1/booking/{id} returns 500

### ISSUE THREAD

**Issue by Pyskaczu** [devonfw/my-thai-star#372]
### Expected behavior

As an API client, I want to call get booking of a given id so that I can get booking details.

### Actual behavior
<!doctype html>
<html lang="en">

<head>
	<title>HTTP Status 500 – Internal Server Error</title>
	<style type="text/css">
		body {
			font-family: Tahoma, Arial, sans-serif;
		}
		h1,
		h2,
		h3,
		b {
			color: white;
			background-color: #525D76;
		}
		h1 {
			font-size: 22px;
		}
		h2 {
			font-size: 16px;
		}
		h3 {
			font-size: 14px;
		}
		p {
			font-size: 12px;
		}
		a {
			color: black;
		}
		.line {
			height: 1px;
			background-color: #525D76;
			border: none;
		}
	</style>
</head>

<body>
	<h1>HTTP Status 500 – Internal Server Error</h1>
</body>

</html>

### Steps to reproduce (bug) / Use Case of feature request (enhancement)
Make an authorized GET API request to host/api/services/rest/bookingmanagement/v1/booking/{id}

### Affected version:

* OS: Windows/Linux/Mac?
* Browser: Chrome/Firefox/Safari?

**Comment by Pyskaczu** [comment]
/api/services/rest/bookingmanagement/v1/table/{id} is not working as well

**Comment by Pyskaczu** [comment]
No issue as "bookingToken" was used instead of "id"

**Comment by isandesh1986** [comment]
After using the right data - all the mythaistar endpoints are working fine as expected.

**Comment by markusschuh** [comment]
Does that mean, the API endpoint can be made to return 500 (Internal Server Error) by upload the "wrong" data?

If yes, I'd say, this is indeed a bug. According to https://raw.githubusercontent.com/devonfw/my-thai-star/develop/swagger/mythaistar.yaml  the return value in this case should be 400 (Bad request. Parser data error.)

Other REST API implementation meanwhile use 422 (Unprocessable Entity) - but since there is no fixed standard, this is always open to some discussion. 

Nevertheless within http standard any 5xx is reserved for server side errors, while the 4xx means error state, that the client side can fix. So it is important to return a 4xx status for the wrong set of input parameters.
