### ISSUE TITLE
Replacement of current Mail Service implementation in My Thai Star application with Mail Microservices

### ISSUE THREAD

**Issue by AbhayChandel** [devonfw/my-thai-star#58]
As per the pull request #45, Mail service implementation in My Thai Star application is internal component of the application. Whereas the preferred approach would be to integrate it as a standard Devon/OASP module into the application. In the light of the fact that we are already towards the completion of developing a separate Mail microservice for devonfw, it would be desirable to inject the same in place of My Thai Star application's current internal mail service component. For further details  follow the link below.

[Pull Request #45](https://github.com/oasp/my-thai-star/pull/45)

**Comment by ivanderk** [comment]
That is NOT the User Story which we defined. 

As a developer I want to be able to have a boolean configuration option "devonfw.sample.microservices" in the application-config of the sample app so that I can optionally choose to see how microservices components are implemented in the 

As a developer I want to have the configuration option "devonfw.sample.microservices" in the application-config of the sample app by default set to *false* so that I am not bothered by having to install all the micro services paraphernalia every time I just want to run the app

We can replace the full Twtter and email implementation by a Mock implementation for the common case when "devonfw.sample.microservices" is set to false

Please check with @jajimene and @ssarmokadam
